/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import java.io.IOException;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        String path = System.getProperty("user.dir");
        System.out.println(path);
        Bitmap test = new Bitmap("baldy-8bit.bmp", "test3", "grayScale");

    }

}
